spring:
  datasource:
    url: jdbc:mysql://www.91iedu.com:3391/team06?useSSL=false&characterEncoding=utf-8&serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: team06
    password: team06
    type: org.springframework.jdbc.datasource.SimpleDriverDataSource

  mvc:
    view:
      suffix: .html
      prefix: classpath:/static/

mybatis:
  configuration:
    cache-enabled: true
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl
    map-underscore-to-camel-case: true
  type-aliases-package: com.iedu.demo.demo.entity
#
#logging:
#  level:
#    com.iedu.demo.demo.dao:debug

server:
  port: 9090
